version: '3.8'

services:
  envers-demo-db:
    container_name: envers-demo-postgres
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: password
