server:
  port: 8081

# https://docs.redhat.com/en/documentation/red_hat_jboss_web_server/2/html/hibernate_core_guide/envers_configuration_properties#Envers_Configuration_Properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
